### ISSUE TITLE
http://api.metacpan.org/v0/module/  returns a list of modules

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/cpan-api#411] opened 2015-05-13 08:31 UTC
For example http://api.metacpan.org/v0/module/Dist::Zilla returns a hash with a key 'modules' which is an array of 1 element. Why that an array? Are there cases when this will return a different number of entries?

**Comment by rwstauner** [comment] 2015-05-13 13:38
Yes: https://api.metacpan.org/v0/module/App::Cmd::Tester

**Comment by ranguard** [comment] 2016-03-05 13:50
Not a bug - closing

**Closed by ranguard** 2016-03-05 13:50 UTC
