### ISSUE TITLE
.pod files are not available, 404 is returned instead

### ISSUE THREAD

**Issue by mephinet** [CPAN-API/cpan-api#494] opened 2016-06-09 15:31 UTC
[Searching for Moose::Manual](https://v1.metacpan.org/search?q=moose%3A%3Amanual&search_type=modules) correctly yields the link to Moose/Manual.pod. Clicking on this [link](https://v1.metacpan.org/pod/distribution/Moose/lib/Moose/Manual.pod), however, results in a 404 error.

**Comment by kentfredric** [comment] 2016-06-09 16:54
This is a `v1` issue:

https://v1.metacpan.org/pod/distribution/Moose/lib/Moose/Manual.pod # bad
https://metacpan.org/pod/distribution/Moose/lib/Moose/Manual.pod # good

Similarly, I have 4 releases I shipped since May 29th that are all missing now.

https://v1.metacpan.org/author/KENTNL
vs
https://metacpan.org/author/KENTNL

```
Dist-Zilla-Role-Version-Sanitize-0.002002
Dist-Zilla-App-Comm…-dumpwith-0.003001
Parse-Method-Signatures-1.003017
Carp-Clan-6.06
```

All 4 can be searched for via v1, but all 4 result in 404s.

**Comment by mickeyn** [comment] 2016-06-09 22:56
The links above work now (with the deployment of https://github.com/CPAN-API/metacpan-web/pull/1715)
This was a WEB issues, not API.

Can you please verify and close?

**Comment by kentfredric** [comment] 2016-06-10 00:30
https://v1.metacpan.org/pod/distribution/Carp-Clan/lib/Carp/Clan.pod # is still exhibiting the same failure

**Comment by mickeyn** [comment] 2016-06-10 10:08
should be fixed now, please verify

**Comment by kentfredric** [comment] 2016-06-10 10:12
Confirmed, all the failure cases I found and mentioned here are fixed.

**Comment by mickeyn** [comment] 2016-06-11 18:08
great. closing then.

**Closed by mickeyn** 2016-06-11 18:08 UTC
